export class ErrorInterceptor {
    async catch(_: Error): Promise<void> {}
}
